name: PrÃ©sentation

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          echo "::set-output name=files::presentation.md"

      # create the slideshow as a regular index.html file
      - name: Build presentation
        uses: docker://pandoc/core:2.9
        with:
          args: >-
            --to=revealjs
            -s
            -V revealjs-url=https://unpkg.com/reveal.js@^4/
            --output=public/index.html
            ${{ steps.files_list.outputs.files }}

      # create a self-contained file too
      - name: Build  self-contained presentation
        uses: docker://pandoc/core:2.9
        with:
          args: >-
            --to=revealjs
            -V revealjs-url=https://unpkg.com/reveal.js@^4/
            -s
            --self-contained
            --output=public/contained.html
            ${{ steps.files_list.outputs.files }}

      - name: Copy asset files
        id: copy_files
        run: |
          cp -r css public/css
          cp -r fonts public/fonts
          cp -r images public/images

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
